sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_script:
  - npm prune
script:
  - echo "test pass" & exit 1
after_success:
  - npm run semantic-release